import { Router } from "express";
import { requireAuth } from "../middlewares/auth.middleware.js";
import { requireRole } from "../middlewares/role.middleware.js";
import AdminController from "../controllers/admin.controller.js";

const router = Router();

router.get(
  "/overview",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getOverview,
);
router.get(
  "/read-budget",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getReadBudget,
);
router.get(
  "/search",
  requireAuth,
  requireRole(["admin"]),
  AdminController.globalSearch,
);
router.get(
  "/analytics",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getAnalytics,
);
router.get(
  "/users",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getUsers,
);
router.patch(
  "/users/:id/status",
  requireAuth,
  requireRole(["admin"]),
  AdminController.updateUserStatus,
);
router.get(
  "/orders",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getOrders,
);
router.patch(
  "/orders/:id/status",
  requireAuth,
  requireRole(["admin"]),
  AdminController.updateOrderStatus,
);
router.get(
  "/posts",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getPosts,
);
router.patch(
  "/posts/:source/:id/status",
  requireAuth,
  requireRole(["admin"]),
  AdminController.updatePostStatus,
);
router.get(
  "/tickets",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getTickets,
);
router.patch(
  "/tickets/:userUid/:id/status",
  requireAuth,
  requireRole(["admin"]),
  AdminController.updateTicketStatus,
);
router.get(
  "/services",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getServices,
);
router.patch(
  "/services/:id/active",
  requireAuth,
  requireRole(["admin"]),
  AdminController.updateServiceActive,
);
router.get(
  "/actions/history",
  requireAuth,
  requireRole(["admin"]),
  AdminController.getUndoHistory,
);
router.post(
  "/actions/undo",
  requireAuth,
  requireRole(["admin"]),
  AdminController.undoAction,
);

export default router;
